export const uCommunity = 'https://steamcommunity.com'
export const uStore = 'https://store.steampowered.com'
export const uApi = 'https://api.steampowered.com'

export const uInventory = uCommunity + '/inventory'
export const uInventoryProfiles = uInventory + '/profiles'

export const uDev = uCommunity + '/dev'
export const uApiKey = uDev + '/apikey'
export const uApiKeyRegister = uDev + '/registerkey'
export const uApiKeyRevoke = uDev + '/revokekey'

export const uApiEconService = uApi + '/IEconService'
export const uApiEconCancelTradeV1 = uApiEconService + '/CancelTradeOffer/v1'
export const uApiEconDeclineTradeV1 = uApiEconService + '/DeclineTradeOffer/v1'
export const uApiEconGetTradesV1 = uApiEconService + '/GetTradeOffers/v1'
export const uApiEconGetTradeV1 = uApiEconService + '/GetTradeOffer/v1'
export const uApiEconGetTradeSummaryV1 = uApiEconService + '/GetTradeOffersSummary/v1'

export const uApiUser = uApi + '/ISteamUser'
export const uApiUserResolveVanityURLV1 = uApiUser + '/ResolveVanityURL/v0001'

export const uApiPlayer = uApi + '/IPlayerService'
export const uApiPlayerGetRecentlyPlayedGamesV1 = uApiPlayer + '/GetRecentlyPlayedGames/v1'
export const uApiPlayerGetOwnedGamesV1 = uApiPlayer + '/GetOwnedGames/v1'
export const uApiPlayerGetSteamLevelV1 = uApiPlayer + '/GetSteamLevel/v1'
export const uApiPlayerGetBadgesV1 = uApiPlayer + '/GetBadges/v1'
export const uApiPlayerGetCommunityBadgeProgressV1 = uApiPlayer + '/GetCommunityBadgeProgress/v1'

export const uTradeoffer = uCommunity + '/tradeoffer'
export const uTradeofferNew = uTradeoffer + '/new'
export const uTradeofferNewSend = uTradeofferNew + '/send'

export const uMarket = uCommunity + '/market'
export const uMarketListings = uMarket + '/listings'
export const uMarketSellItem = uMarket + '/sellitem'
export const uMarketPriceHistory = uMarket + '/pricehistory'
export const uMarketSearch = uMarket + '/search/render'
export const uMarketOrderHistogram = uMarket + '/itemordershistogram'
export const uMarketSellListings = uMarket + '/mylistings/render'
export const uMarketMultisell = uMarket + '/multisell'
export const uMarketRemoveListing = uMarket + '/removelisting'
export const uMarketPriceOverview = uMarket + '/priceoverview'

export const uStoreApi = uStore + '/api'
export const uStoreAppDetails = uStoreApi + '/appdetails'
export const uStorePackagedetails = uStoreApi + '/packagedetails'
export const uStoreSearch = uStore + '/search/results'
export const uStoreBundlePage = uStore + '/bundle'

export const uStoreCart = uStore + '/cart'
export const uStoreCheckout = uStore + '/checkout'
export const uCartCheckoutGetFinalPrice = uStoreCheckout + '/getfinalprice'
export const uCartCheckoutInitTransaction = uStoreCheckout + '/inittransaction'
export const uCartCheckoutFinalizeTransaction = uStoreCheckout + '/finalizetransaction'

